# Generated by Django 3.1.4 on 2020-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на сайт компании'),
        ),
    ]
